name: minimal-gnn
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies for Colmena
  - python==3.8.*
  - jupyterlab
  - pytest
  - flake8
  - pip

  - pip:
      - -r requirements.txt
      - -e .  # Installs our utilities 
