name: minimal-gnn
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies for Colmena
  - python==3.8.*
  - jupyterlab
  - pytest
  - flake8
  - pip

  # Dependencies from the molecular design app
  - matplotlib==3.3.3
  - scikit-learn==1.1.1
  - rdkit==2019.09.3
  - psutil
  - tqdm

  # Pip packages for all of them
  - pip:
      - -e .  # Installs the 
      - tensorflow==2.8.*
